#include <iostream>
// This header is generated by build. 
#include "../bin/shaderHeaders/ballVertex_shader.hpp"

#include"meshUtils.hpp"
#include"ioUtils.hpp"

int main(int argc, char* argv[]){
    std::vector<float> testBuffer = buildUVSphereMesh(64, 64);
    writeBufferToPly(testBuffer, "test.ply");

    return 0;
}