#include <iostream>
// This header is generated by build. 
#include "../bin/shaderHeaders/vertex_shader.hpp"

int main(int argc, char* argv[]){
    // Print shader as a placeholder for now
    std::cout << VERTEX_SHADER_SRC << std::endl;
}